baseURL = 'https://pboxkorea.com'
languageCode = 'en-us'
title = 'PBOX Korea'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Publish'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Category'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.123.8"
